### ISSUE TITLE
Interp Commands dont work in cs2

### ISSUE THREAD

**Issue by damiensprinkle** [pynacl/cs2#1]
// Rates
cl_cmdrate "128"
cl_updaterate "128"
cl_interp "0.015625"
cl_interp_ratio "1"
cl_interpolate "1"
cl_lagcompensation "1"

**Comment by pynacl** [comment]
Ah you're right, these were removed on Sept 14th: ![diff](https://files.bo3.gg/uploads/image/17827/image/webp-dca88a057a4b2399cb568941a10ed3b3.webp)
Hope that doesn't mean they are forcing everyone to use `0.046875`

**Comment by pynacl** [comment]
Removed them https://github.com/pynacl/cs2/commit/c2ae55de01c381b8d7497dded5492ee805c7b999
